name: Xcode - Build and Analyze

on:
  push:
    branches: [ "macos-main" ]
  pull_request:
    branches: [ "macos-main" ]

jobs:
  build:
    name: Build and analyse
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Show Xcode version
        run: xcode-select -p

      - name: Install the Apple certificate
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_P12 }}
          P12_PASSWORD: ${{ secrets.PASSWORD_P12 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      - name: Project information
        run: |
          xcodebuild -list

      - name: Build
        env:
          scheme: ${{ 'OlaRadioUI' }}
          destination: ${{ 'platform=macOS' }}
        run: |
          xcodebuild clean build analyze -scheme OlaRadioUI -destination platform=macOS -showBuildTimingSummary | xcpretty && exit ${PIPESTATUS[0]}

